### ISSUE TITLE
Support gray/silver

### ISSUE THREAD

**Issue by simison** [CodeOtter/goldmansachs#1]
Why stop on yellow/gold?

**Comment by CodeOtter** [comment]
Between the 11th and 17th century, Western Africa was the primary source of gold for international markets.  In fact, medieval West Africa exported 3.5 tons of gold per year. (https://ojs.lib.byu.edu/spc/index.php/CCR/article/download/12512/12393)

Silver was mostly used as a store of value by Europe and China, so printing mansa characters in silver would be historically inaccurate.
